present:
	presenterm --config-file presenterm.config.yaml --validate-overflows --validate-snippets numpy_talk.md

pdf:
	presenterm --export-pdf --config-file presenterm.config.yaml --validate-overflows --validate-snippets numpy_talk.md

html:
	presenterm --export-html --config-file presenterm.config.yaml --validate-overflows --validate-snippets numpy_talk.md

